import type { Metadata } from "next";
import { SeoLandingPage, type SeoLandingData } from "../../components/SeoLandingPage";
const siteUrl = "https://virtualagentai.org";
export const metadata: Metadata = { title: "24/7 After-Hours AI Answering Service", description: "Answer calls after hours, on weekends, and during overflow with AI intake, appointment booking, urgent call routing, and team alerts.", alternates: { canonical: `${siteUrl}/services/after-hours-answering` }, openGraph: { type: "website", url: `${siteUrl}/services/after-hours-answering`, title: "24/7 After-Hours AI Answering Service", description: "Protect nights, weekends, and overflow calls with a defined response workflow.", siteName: "Virtual Agent AI" } };
const data: SeoLandingData = {
  path: "/services/after-hours-answering", eyebrow: "AFTER-HOURS AI ANSWERING", title: "Keep valuable calls moving when the office is closed.", intro: "Our after-hours AI answering service responds during nights, weekends, holidays, lunch breaks, and overflow periods. It identifies the caller, captures the request, applies your urgency rules, and completes the approved booking or escalation path.", promise: "Fewer overnight opportunities lost, fewer unnecessary interruptions for on-call staff, and a clear record of every request.", serviceType: "After-Hours AI Answering Service",
  benefits: [{ title: "Answer immediately", text: "Give every caller a professional response instead of voicemail when employees are unavailable or the business is closed." }, { title: "Protect the on-call team", text: "Use objective questions to separate true emergencies and high-priority requests from routine work that can be booked or followed up later." }, { title: "Start the next business day organized", text: "Deliver structured summaries, booked appointments, priority callbacks, and unresolved exceptions to the right people." }],
  sectionTitle: "A separate call plan for the hours when staffing is limited.", sectionIntro: "After-hours workflows need clear definitions for urgent, emergency, routine, existing-customer, and out-of-area calls. Each path should state exactly what the caller is told and who receives the request.",
  steps: [{ title: "Capture identity and location", text: "Collect the caller's name, callback number, service address, and existing-customer status early in the conversation." }, { title: "Understand the situation", text: "Record what is happening, when it began, and the objective facts your business uses to judge urgency." }, { title: "Apply the approved path", text: "Transfer, alert, book, create a priority callback, or document a routine request based on your rules." }, { title: "Confirm the outcome", text: "Tell the caller what happens next without promising availability, arrival times, or actions the system cannot verify." }],
  fitTitle: "Choose full-time, overflow, or after-hours-only coverage.", fitText: "The schedule can support an existing receptionist during busy periods or provide complete coverage when the office closes.", fitPoints: ["Evenings and overnight calls", "Weekend and holiday coverage", "Lunch and meeting overflow", "On-call escalation rules", "Next-day appointment booking", "Priority callback creation"],
  faqs: [{ question: "Can I use the service only outside business hours?", answer: "Yes. Calls can be forwarded according to your phone schedule so the AI receptionist handles only nights, weekends, holidays, lunch periods, or other defined windows." }, { question: "Can it route emergency calls?", answer: "It can apply your objective urgency questions and route the call through approved transfers, alerts, priority callbacks, or public emergency instructions. It should not diagnose a problem or invent safety advice." }, { question: "Can routine calls be booked for the next day?", answer: "Yes. The AI can qualify the request and offer eligible future availability so routine work does not become a voicemail backlog." }, { question: "What happens if the on-call person does not answer?", answer: "The workflow should include a backup path, such as another contact, a priority alert, a documented callback request, or an accurate explanation to the caller." }],
  related: [{ href: "/services/ai-call-answering", label: "AI call answering" }, { href: "/ai-answering-service-for-home-services", label: "Home service answering" }, { href: "/blog/after-hours-answering-service", label: "After-hours guide" }]
};
export default function Page() { return <SeoLandingPage data={data} />; }
