import type { Metadata } from "next";
import { SeoLandingPage, type SeoLandingData } from "../components/SeoLandingPage";
const siteUrl = "https://virtual-agent-ai.typical-sammich.chatgpt.site";
export const metadata: Metadata = { title: "AI Agent for HVAC Companies and Contractors", description: "An HVAC AI Agent that answers heating and cooling calls, qualifies service requests, books appointments, and protects nights and overflow.", alternates: { canonical: `${siteUrl}/ai-agent-for-hvac` }, openGraph: { type: "website", url: `${siteUrl}/ai-agent-for-hvac`, title: "AI Agent for HVAC Calls", description: "Answer more heating and cooling calls without interrupting the field team.", siteName: "Virtual Agent AI" } };
const data: SeoLandingData = {
  path: "/ai-agent-for-hvac", eyebrow: "AI AGENT FOR HVAC COMPANIES", title: "Keep seasonal call spikes from turning into missed opportunities.", intro: "Virtual Agent AI configures an HVAC AI Agent around your heating, cooling, maintenance, and replacement workflows. It answers immediately, understands the request, checks location and service fit, then books, routes, or creates the correct follow-up.", promise: "Consistent call coverage during peak demand, evenings, weekends, and the moments your office cannot pick up.", serviceType: "AI Agent for HVAC Companies",
  benefits: [{ title: "Handle high-volume weather days", text: "Support simultaneous calls when extreme heat or cold creates more demand than one phone queue can manage." }, { title: "Separate service from sales", text: "Identify repairs, maintenance, tune-ups, estimates, installations, warranty questions, and existing-customer requests." }, { title: "Book with the right details", text: "Capture system type, symptoms, location, timing, customer status, and appointment requirements before scheduling." }],
  sectionTitle: "A call workflow that understands HVAC demand.", sectionIntro: "Your services, territories, hours, maintenance plans, availability, on-call process, and escalation rules shape every conversation.",
  steps: [{ title: "Identify intent", text: "Understand whether the caller needs repair, maintenance, replacement, an estimate, or account help." }, { title: "Gather system context", text: "Collect approved details about the equipment, symptoms, property, and timing." }, { title: "Choose the next action", text: "Book an eligible appointment, route a sales opportunity, or escalate an urgent request." }, { title: "Create the handoff", text: "Deliver the conversation outcome and useful customer details to the right team." }],
  fitTitle: "Built for residential and light-commercial HVAC operations.", fitText: "The AI Agent can support the front desk rather than forcing dispatchers and technicians to answer every first call.", fitPoints: ["No-cooling and no-heat calls", "Maintenance scheduling", "Replacement estimates", "Membership inquiries", "Seasonal overflow", "After-hours requests"],
  faqs: [{ question: "Can an HVAC AI Agent handle several calls at once?", answer: "Yes. Concurrent answering can help during seasonal surges, advertising campaigns, and weather-driven demand." }, { question: "Can it recognize an existing maintenance-plan customer?", answer: "The workflow can ask for customer details and, where supported, use connected systems or routing rules to handle members appropriately." }, { question: "Does the AI Agent diagnose HVAC equipment?", answer: "No. It collects approved intake information and routes the request. Diagnosis and safety decisions remain with qualified professionals." }],
  related: [{ href: "/services/lead-qualification", label: "Lead qualification" }, { href: "/services/appointment-booking", label: "Appointment booking" }, { href: "/blog/stop-missing-business-calls", label: "Missed-call playbook" }],
};
export default function Page() { return <SeoLandingPage data={data} />; }
