import type { Metadata } from "next";
import { SeoLandingPage, type SeoLandingData } from "../../components/SeoLandingPage";
const siteUrl = "https://virtualagentai.org";
export const metadata: Metadata = { title: "AI Appointment Booking by Phone", description: "Turn qualified inbound calls into booked appointments with conversational AI scheduling, live availability, business rules, and confirmations.", alternates: { canonical: `${siteUrl}/services/appointment-booking` }, openGraph: { type: "website", url: `${siteUrl}/services/appointment-booking`, title: "AI Appointment Booking by Phone", description: "Qualify callers and schedule the right appointment before the call ends.", siteName: "Virtual Agent AI" } };
const data: SeoLandingData = {
  path: "/services/appointment-booking", eyebrow: "AI APPOINTMENT BOOKING", title: "Turn qualified phone calls into confirmed appointments while intent is high.", intro: "AI appointment booking keeps the caller in the conversation, applies your eligibility and scheduling rules, offers valid availability, and confirms the right appointment before the person hangs up.", promise: "Less scheduling back and forth, fewer abandoned inquiries, and more complete appointments on the calendar.", serviceType: "AI Appointment Booking Service",
  benefits: [{ title: "Qualify before offering a time", text: "Confirm service type, location, customer status, urgency, and any other rules that determine where the appointment belongs." }, { title: "Use real availability", text: "Read eligible times from the approved calendar or scheduling workflow and recheck the slot before confirming." }, { title: "Send complete booking details", text: "Record the appointment with caller information, service context, required notes, and the confirmation process your business uses." }],
  sectionTitle: "A booking workflow that follows the same rules as your best coordinator.", sectionIntro: "Useful scheduling depends on operational details. Service areas, appointment types, durations, buffers, staff skills, locations, and urgent-call paths all shape what the AI may offer.",
  steps: [{ title: "Identify the need", text: "Understand the service, reason for the appointment, location, customer type, and desired timing." }, { title: "Confirm eligibility", text: "Apply the rules that determine whether the request may be booked and which calendar or team should receive it." }, { title: "Offer valid times", text: "Present a focused set of available options and let the caller choose without leaving the phone conversation." }, { title: "Confirm and notify", text: "Create the appointment, repeat the details, and send the correct confirmation and team summary." }],
  fitTitle: "Best for appointment-based businesses with defined scheduling rules.", fitText: "The service is strongest when the business can explain which calls qualify, what information must be collected, and how availability is organized.", fitPoints: ["Service and estimate appointments", "Consultation scheduling", "New-patient requests", "Diagnostic and repair visits", "Showing and sales appointments", "Rescheduling and confirmation workflows"],
  faqs: [{ question: "Can an AI receptionist book appointments during the call?", answer: "Yes. It can collect required details, check eligible availability, create the appointment, and confirm the next steps while the caller remains on the phone." }, { question: "How does it prevent the wrong type of appointment?", answer: "The workflow uses qualification and eligibility rules before showing times. Requests that do not fit a defined booking path can be routed to a person." }, { question: "Can it handle several calendars?", answer: "Yes, when the calendars and routing logic can be connected safely. The setup defines which services, locations, employees, or territories belong to each calendar." }, { question: "What happens if the calendar is unavailable?", answer: "The failure path can collect the request, explain that confirmation is pending, and create an immediate follow-up task instead of promising an unverified time." }],
  related: [{ href: "/services/lead-qualification", label: "Lead qualification" }, { href: "/services/ai-call-answering", label: "AI call answering" }, { href: "/blog/ai-appointment-scheduling", label: "Scheduling guide" }]
};
export default function Page() { return <SeoLandingPage data={data} />; }
