import type { Metadata } from "next";
import { SeoLandingPage, type SeoLandingData } from "../../components/SeoLandingPage";
const siteUrl = "https://virtual-agent-ai.typical-sammich.chatgpt.site";
export const metadata: Metadata = { title: "AI Lead Qualification by Phone", description: "Qualify inbound leads by phone with custom questions for fit, intent, urgency, readiness, and the right sales or service next step.", alternates: { canonical: `${siteUrl}/services/lead-qualification` }, openGraph: { type: "website", url: `${siteUrl}/services/lead-qualification`, title: "AI Lead Qualification by Phone", description: "Capture the facts your team needs before a lead reaches the next step.", siteName: "Virtual Agent AI" } };
const data: SeoLandingData = {
  path: "/services/lead-qualification", eyebrow: "AI LEAD QUALIFICATION", title: "Ask the right questions before your team spends time on the lead.", intro: "AI lead qualification uses a natural phone conversation to capture fit, intent, urgency, and readiness. Each caller receives a useful next step while your team gets the context needed to prioritize, book, transfer, or follow up.", promise: "Better prepared sales conversations, faster routing for valuable opportunities, and less time spent chasing incomplete leads.", serviceType: "AI Lead Qualification Service",
  benefits: [{ title: "Use business-specific qualification rules", text: "Check the services, locations, customer types, timelines, and objective criteria that determine whether the inquiry fits." }, { title: "Adapt questions to the caller", text: "Ask relevant follow-up questions based on what the person has already said instead of reading one rigid checklist." }, { title: "Route by outcome, not a generic score", text: "Book ready leads, transfer urgent opportunities, nurture longer-term prospects, and send uncertain cases to a person for review." }],
  sectionTitle: "Qualification that helps the caller move forward.", sectionIntro: "Good qualification should reduce repetition and confusion. The workflow collects only the information needed to determine a safe, useful next step.",
  steps: [{ title: "Confirm fit", text: "Check whether the requested service, location, matter, property, or customer type matches the business." }, { title: "Understand intent", text: "Identify whether the caller is researching, comparing options, requesting help, or ready to schedule." }, { title: "Measure urgency", text: "Capture objective timing, deadline, safety, or active-loss details that change how quickly the team should respond." }, { title: "Complete the next step", text: "Book, transfer, route, summarize, or schedule follow-up based on approved business rules." }],
  fitTitle: "Useful wherever the value of a lead depends on more than contact information.", fitText: "The business defines the criteria and remains responsible for sensitive, uncertain, regulated, or high-consequence decisions.", fitPoints: ["Service-area qualification", "New-client intake", "Buyer and seller screening", "Borrower inquiry routing", "Quote-request qualification", "Urgency and readiness capture"],
  faqs: [{ question: "Can AI qualify leads over the phone?", answer: "Yes. Conversational AI can ask branching questions, capture responses, apply approved rules, and create a structured summary during the inbound call." }, { question: "What information should it collect?", answer: "Collect the minimum information needed to understand fit, intent, urgency, readiness, and the next action. Sensitive or unnecessary data should not be requested." }, { question: "Can it automatically reject a lead?", answer: "Only objective, low-risk criteria should be automated. Uncertain, sensitive, regulated, or high-value situations should be routed to a person instead of being rejected by the system." }, { question: "Can qualified leads book immediately?", answer: "Yes. When the caller meets the approved rules, the workflow can transfer the call or offer eligible appointment times without waiting for a callback." }],
  related: [{ href: "/services/appointment-booking", label: "Appointment booking" }, { href: "/ai-receptionist-for-law-firms", label: "Law firm intake" }, { href: "/blog/ai-lead-qualification", label: "Lead qualification guide" }]
};
export default function Page() { return <SeoLandingPage data={data} />; }
