import type { Metadata } from "next";
import { SeoLandingPage, type SeoLandingData } from "../../components/SeoLandingPage";
const siteUrl = "https://virtualagentai.org";
export const metadata: Metadata = { title: "24/7 AI Call Answering Service", description: "Answer inbound business calls 24/7 with natural conversation, custom FAQs, lead capture, call routing, and instant summaries.", alternates: { canonical: `${siteUrl}/services/ai-call-answering` }, openGraph: { type: "website", url: `${siteUrl}/services/ai-call-answering`, title: "24/7 AI Call Answering Service", description: "Reliable business call coverage built around your services, hours, and routing rules.", siteName: "Virtual Agent AI" } };
const data: SeoLandingData = {
  path: "/services/ai-call-answering", eyebrow: "24/7 AI CALL ANSWERING", title: "Every inbound call gets a clear, professional first response.", intro: "Our AI call answering service picks up when your team is busy, after hours, or handling another customer. It speaks naturally, uses approved business information, identifies why the person called, and completes the next action your workflow allows.", promise: "Immediate call coverage with consistent answers, organized intake, and fewer callers sent to voicemail.", serviceType: "24/7 AI Call Answering Service",
  benefits: [
    { title: "Always available", text: "Cover every call, overflow only, nights and weekends, or a custom schedule without relying on a single phone queue." },
    { title: "Built from your business knowledge", text: "Use your services, locations, hours, policies, common questions, terminology, and approved answers during the conversation." },
    { title: "Designed to complete a next step", text: "Route, transfer, qualify, book, notify, or create a follow-up task instead of leaving your team with an unstructured voicemail." },
  ],
  sectionTitle: "Call answering that connects directly to operations.", sectionIntro: "The first response should reduce work for the team, not create another inbox. Each call type is mapped to an approved outcome and a clear handoff.",
  steps: [{ title: "Answer", text: "Use the correct greeting and identify the caller's reason for contacting the business." }, { title: "Understand", text: "Ask relevant follow-up questions based on the service, customer type, location, and urgency." }, { title: "Act", text: "Complete the eligible booking, transfer, qualification, routing, or information request." }, { title: "Report", text: "Send the team a concise summary, captured details, and the action already completed." }],
  fitTitle: "Flexible coverage for businesses that depend on the phone.", fitText: "Use the AI as the primary receptionist, an after-hours answering service, or overflow support when employees are unavailable.", fitPoints: ["24/7 inbound call answering", "Overflow and peak-call support", "Custom greetings and FAQs", "Multiple simultaneous calls", "Live transfer rules", "Call summaries and notifications"],
  faqs: [{ question: "Can the AI answer more than one call at a time?", answer: "Yes. An AI phone system can support simultaneous conversations, which helps during advertising spikes, emergencies, seasonal demand, and other high-volume periods." }, { question: "Can callers reach a real person?", answer: "Yes. The workflow can transfer specific callers or situations to approved people, departments, backup lines, or on-call contacts." }, { question: "Can it answer questions about my business?", answer: "Yes. It uses the approved services, hours, locations, policies, and answers supplied during setup. Questions outside the approved scope can be escalated or captured for follow-up." }, { question: "Can I use it only after hours?", answer: "Yes. Coverage can be designed for after-hours calls, overflow, specific call types, or full-time reception." }],
  related: [{ href: "/services/after-hours-answering", label: "After-hours answering" }, { href: "/services/lead-qualification", label: "Lead qualification" }, { href: "/ai-receptionist-for-small-business", label: "Small business AI receptionist" }]
};
export default function Page() { return <SeoLandingPage data={data} />; }
