import type { Metadata } from "next";
import { SeoLandingPage, type SeoLandingData } from "../components/SeoLandingPage";
const siteUrl = "https://virtual-agent-ai.typical-sammich.chatgpt.site";
export const metadata: Metadata = { title: "AI Agent for Plumbers and Plumbing Companies", description: "A plumbing AI Agent that answers calls, identifies urgent jobs, checks service areas, books appointments, and sends dispatch-ready summaries 24/7.", alternates: { canonical: `${siteUrl}/ai-agent-for-plumbers` }, openGraph: { type: "website", url: `${siteUrl}/ai-agent-for-plumbers`, title: "AI Agent for Plumbing Calls", description: "Turn more plumbing calls into organized jobs and appointments.", siteName: "Virtual Agent AI" } };
const data: SeoLandingData = {
  path: "/ai-agent-for-plumbers", eyebrow: "AI AGENT FOR PLUMBING COMPANIES", title: "Answer the plumbing call before the homeowner calls someone else.", intro: "Virtual Agent AI builds a plumbing AI Agent that answers new and existing customers at any hour. It identifies the issue, captures the property address, checks service fit, applies your urgency rules, and books or routes the next step.", promise: "Faster response for homeowners and cleaner job information for dispatch, technicians, and owners.", serviceType: "AI Agent for Plumbers",
  benefits: [
    { title: "Capture jobs while the crew is working", text: "The AI Agent answers when technicians are driving, on a job, after hours, or helping another customer." },
    { title: "Recognize urgent plumbing situations", text: "Use company-approved questions for active leaks, backups, no-water calls, water-heater problems, and other time-sensitive requests." },
    { title: "Give dispatch a useful summary", text: "Record the caller, address, issue, urgency, access details, and the appointment or handoff already completed." },
  ],
  sectionTitle: "A plumbing call flow built around real service decisions.", sectionIntro: "The workflow uses your service area, job types, hours, availability, pricing language, emergency definitions, and on-call contacts.",
  steps: [{ title: "Understand the issue", text: "Ask what is happening, when it began, which fixture or system is affected, and whether damage is active." }, { title: "Check service fit", text: "Confirm location, property type, customer status, and whether the requested work matches your services." }, { title: "Book or escalate", text: "Offer an eligible time or route urgent calls to the approved on-call path." }, { title: "Update the team", text: "Send a concise record so the next person can act without replaying a voicemail." }],
  fitTitle: "Useful for residential, commercial, and emergency plumbing teams.", fitText: "Use the AI Agent as primary reception, after-hours coverage, or overflow when the office is busy.", fitPoints: ["Emergency plumbing intake", "Drain and sewer calls", "Water-heater appointments", "Leak and fixture requests", "Service-area screening", "After-hours dispatch alerts"],
  faqs: [{ question: "Can the AI Agent tell if a plumbing call is urgent?", answer: "It can ask objective questions approved by your company and follow the escalation path you define. It does not replace emergency services or a technician's professional judgment." }, { question: "Can it book directly into our calendar?", answer: "Yes, when the scheduling system and workflow support an integration. Booking rules can account for service type, coverage area, availability, and required appointment details." }, { question: "Can customers still reach a person?", answer: "Yes. The AI Agent can transfer defined calls to dispatch, an owner, an office employee, or an on-call technician." }],
  related: [{ href: "/services/after-hours-answering", label: "After-hours answering" }, { href: "/services/appointment-booking", label: "Appointment booking" }, { href: "/ai-answering-service-for-home-services", label: "Home service answering" }],
};
export default function Page() { return <SeoLandingPage data={data} />; }
