import type { Metadata } from "next";
import { SeoLandingPage, type SeoLandingData } from "../components/SeoLandingPage";
const siteUrl = "https://virtual-agent-ai.typical-sammich.chatgpt.site";
export const metadata: Metadata = { title: "AI Agent for Dental Offices and Appointment Calls", description: "A dental AI Agent for new-patient calls, appointment requests, routine questions, overflow, and after-hours intake with clear escalation rules.", alternates: { canonical: `${siteUrl}/ai-agent-for-dental-offices` }, openGraph: { type: "website", url: `${siteUrl}/ai-agent-for-dental-offices`, title: "AI Agent for Dental Office Calls", description: "Help patients reach the right next step when the front desk is busy.", siteName: "Virtual Agent AI" } };
const data: SeoLandingData = {
  path: "/ai-agent-for-dental-offices", eyebrow: "AI AGENT FOR DENTAL OFFICES", title: "Give every patient call a calm and organized first response.", intro: "Virtual Agent AI configures a dental-office AI Agent for new-patient inquiries, appointment requests, routine practice questions, overflow, and after-hours intake. The workflow stays within approved administrative information and escalates clinical or sensitive situations appropriately.", promise: "More consistent phone coverage without asking the front desk to abandon the patients already in the office.", serviceType: "AI Agent for Dental Offices",
  benefits: [{ title: "Support a busy front desk", text: "Answer routine and new-patient calls while employees handle check-in, check-out, insurance tasks, and in-office needs." }, { title: "Capture appointment intent", text: "Understand the requested service, patient status, general timing, contact information, and preferred next step." }, { title: "Respect clinical boundaries", text: "Use clear limits for medical questions, urgent symptoms, privacy-sensitive requests, and conversations that require trained staff." }],
  sectionTitle: "Administrative call handling designed around the practice.", sectionIntro: "The workflow uses your hours, locations, services, accepted administrative language, appointment rules, and escalation contacts.",
  steps: [{ title: "Understand the request", text: "Identify whether the caller is a new or existing patient and what administrative help they need." }, { title: "Collect approved details", text: "Gather contact information, service interest, timing, and other nonclinical intake fields." }, { title: "Book or hand off", text: "Offer eligible scheduling options or route the request to front-desk or clinical staff." }, { title: "Document the result", text: "Provide the team with a concise summary and the action already completed." }],
  fitTitle: "Designed for dental practices that depend on responsive scheduling.", fitText: "The AI Agent can cover overflow, lunch, evenings, weekends, or a broader share of routine administrative calls.", fitPoints: ["New-patient inquiries", "Appointment requests", "Routine office FAQs", "Overflow coverage", "After-hours intake", "Staff escalation rules"],
  faqs: [{ question: "Can a dental AI Agent answer medical questions?", answer: "It should not diagnose, recommend treatment, or replace clinical judgment. It can provide approved administrative information and route clinical questions to qualified staff." }, { question: "Can it schedule new patients?", answer: "Yes, when the calendar and office rules support the workflow. It can collect the required administrative details and offer eligible appointment types and times." }, { question: "How are urgent calls handled?", answer: "The practice defines the approved escalation language and contacts. Emergencies can be directed to appropriate emergency resources while other urgent requests follow the practice's on-call or callback process." }],
  related: [{ href: "/services/appointment-booking", label: "Appointment booking" }, { href: "/services/after-hours-answering", label: "After-hours answering" }, { href: "/blog/ai-appointment-scheduling", label: "Scheduling guide" }],
};
export default function Page() { return <SeoLandingPage data={data} />; }
